import type { Metadata } from "next";
import { Sen } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";

const sen = Sen({ subsets: ["latin"], weight: "400"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full" style={{ scrollBehavior: "smooth" }}>
      <body className={`${sen.style.fontFamily} h-full`}>
        <Header />
        <div className="min-h-full">{children}</div>
      </body>
    </html>
  );
}
