import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full" style={{ scrollBehavior: "smooth" }}>
      <body className={`${inter.style.fontFamily} h-full`}>
        <Header />
          <div className="min-h-full">{children}</div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
